baseURL = "https://minium.com.au/openforcefield.org/"
languageCode = "en-us"
title = "OpenFF"
theme = "openff"

enableEmoji = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_title = "<b>open</b> force field"
  header_subtitle = "An open and collaborative approach to better force fields"
  "cc-by-4.0" = "https://creativecommons.org/licenses/by/4.0/"
  "cc-by-nc-nd-4.0" = "https://creativecommons.org/licenses/by/4.0/"
  "arxiv-1.0" = "https://arxiv.org/licenses/nonexclusive-distrib/1.0/license.html"

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/mission/"
    identifier = "about"
    weight = 1

      [[menu.main]]
        name = "Who we are"
        url = "/about/mission/"
        parent = "about"
        identifier = "mission"
        weight = 1

      [[menu.main]]
        name = "Team & Positions"
        url = "/about/team/"
        parent = "about"
        identifier = "team"
        weight = 2

      [[menu.main]]
        name = "FAQ"
        url = "/community/faq/"
        parent = "about"
        identifier = "faq-about"
        weight = 3

  [[menu.main]]
    name = "Science"
    url = "/science/research/"
    weight = 2
    identifier = "science"
    pre = "red"

      [[menu.main]]
        name = "Research"
        url = "/science/research/"
        parent = "science"
        identifier = "research"
        weight = 1

      [[menu.main]]
        name = "Publications"
        url = "/science/publications/"
        parent = "science"
        identifier = "publications"
        weight = 2

      [[menu.main]]
        name = "How to cite"
        url = "/science/how-to-cite/"
        parent = "science"
        identifier = "how-to-cite"
        weight = 3

      [[menu.main]]
        name = "Data"
        url = "/science/data/"
        parent = "science"
        identifier = "data"
        weight = 4

  [[menu.main]]
    name = "Force Fields"
    url = "/force-fields/force-fields/"
    identifier = "force-fields"
    weight = 3

  [[menu.main]]
    name = "Community"
    url = "/community/events/"
    identifier = "community"
    weight = 4

      [[menu.main]]
        name = "Events"
        url = "/community/events/"
        parent = "community"
        identifier = "events"
        weight = 1

  [[menu.main]]
    name = "Partners"
    url = "/partners/"
    identifier = "partners"
    weight = 5

      [[menu.main]]
        name = "Why join"
        url = "/partners/"
        parent = "partners"
        identifier = "why-join"
        weight = 1

      [[menu.main]]
        name = "Industry Partners"
        url = "/partners/industry/"
        parent = "partners"
        identifier = "industry-partners"
        weight = 2

